import 'package:maternal_infant_care/data/models/reminder_model.dart';
import 'package:maternal_infant_care/presentation/viewmodels/user_provider.dart';
import 'package:maternal_infant_care/data/repositories/pregnancy_repository.dart';
import 'package:maternal_infant_care/data/repositories/feeding_repository.dart';
import 'package:maternal_infant_care/data/repositories/sleep_repository.dart';
import 'package:maternal_infant_care/data/repositories/vaccination_repository.dart';
import 'package:uuid/uuid.dart';

class SmartReminderEngine {
  final PregnancyRepository? pregnancyRepo;
  final FeedingRepository? feedingRepo;
  final SleepRepository? sleepRepo;
  final VaccinationRepository? vaccRepo;

  SmartReminderEngine({
    this.pregnancyRepo,
    this.feedingRepo,
    this.sleepRepo,
    this.vaccRepo,
  });

  Future<List<ReminderModel>> generateReminders(UserProfileType profileType) async {
    final List<ReminderModel> reminders = [];

    if (profileType == UserProfileType.pregnant) {
      reminders.addAll(await _generatePregnancyReminders());
    } else if (profileType == UserProfileType.toddlerParent) {
      reminders.addAll(await _generateToddlerReminders());
    }

    // No automatic reminders defined for trying-to-conceive yet

    return reminders;
  }

  Future<List<ReminderModel>> _generatePregnancyReminders() async {
    final List<ReminderModel> list = [];
    final now = DateTime.now();
    
    // 1. Prenatal Vitamin (Daily)
    // Only add if not already present for today? 
    // Usually the main scheduler handles persistence, this engine calculates what SHOULD exist.
    list.add(ReminderModel(
      id: 'smart_vitamin_${now.day}_${now.month}', // Unique per day
      title: 'Take Prenatal Vitamin',
      description: 'Daily vitamin for baby\'s growth.',
      scheduledTime: DateTime(now.year, now.month, now.day, 9, 0), // 9 AM
      type: 'Medical',
      isAutoGenerated: true,
      sourceType: 'general_wellness',
    ));

    // 2. Hydration (Multiple times)
    for (int hour in [10, 14, 17]) {
      list.add(ReminderModel(
         id: 'smart_water_${now.day}_${now.month}_$hour',
         title: 'Stay Hydrated',
         description: 'Drink a glass of water.',
         scheduledTime: DateTime(now.year, now.month, now.day, hour, 0),
         type: 'General',
         isAutoGenerated: true,
         sourceType: 'hydration',
      ));
    }

    // 3. Kick Count (If > 28 weeks)
    if (pregnancyRepo != null) {
      final pregnancy = pregnancyRepo!.getPregnancy();
      if (pregnancy != null) {
         final weeks = pregnancy.currentMonth * 4; // Approx
         // Better logical week calc
         final week = ((DateTime.now().difference(pregnancy.lastPeriodDate).inDays) / 7).floor();
         
         if (week >= 28) {
           list.add(ReminderModel(
             id: 'smart_kick_${now.day}_${now.month}',
             title: 'Kick Count Session',
             description: 'Time to track baby movements.',
             scheduledTime: DateTime(now.year, now.month, now.day, 19, 0), // 7 PM
             type: 'Medical',
             isAutoGenerated: true,
             sourceType: 'kick_monitor',
           ));
         }

         // 4. Weekly Checkup Reminders
         // If current week is a milestone week (12, 20, 28, 36)
         if ([12, 20, 28, 36, 38, 39, 40].contains(week)) {
             list.add(ReminderModel(
               id: 'smart_checkup_week_$week',
               title: 'Week $week Checkup',
               description: 'Schedule your prenatal visit for this week.',
               scheduledTime: DateTime(now.year, now.month, now.day, 10, 0),
               type: 'Medical',
               isAutoGenerated: true,
               sourceType: 'prenatal_schedule',
             ));
         }
      }
    }

    return list;
  }

  Future<List<ReminderModel>> _generateToddlerReminders() async {
    final List<ReminderModel> list = [];
    final now = DateTime.now();

    // 1. Feeding Prediction
    if (feedingRepo != null) {
      // Implement simple logic: Predict next feed based on recent history
      // For brevity, just adding a general meal reminder
      list.add(ReminderModel(
        id: 'smart_lunch_${now.day}_${now.month}',
        title: 'Toddler Lunch Time',
        description: 'Time for a healthy meal.',
        scheduledTime: DateTime(now.year, now.month, now.day, 12, 30),
        type: 'Feeding',
        isAutoGenerated: true,
        sourceType: 'feeding_schedule',
      ));
    }

    // 2. Nap Time
    list.add(ReminderModel(
        id: 'smart_nap_${now.day}_${now.month}',
        title: 'Afternoon Nap',
        description: 'Routine nap for better sleep.',
        scheduledTime: DateTime(now.year, now.month, now.day, 14, 0),
        type: 'Sleep',
        isAutoGenerated: true,
        sourceType: 'sleep_routine',
    ));
    
    // 3. Diaper Check (Periodic)
     list.add(ReminderModel(
        id: 'smart_diaper_check_${now.day}_${now.month}',
        title: 'Diaper Check',
        description: 'Regular hygiene check.',
        scheduledTime: DateTime(now.year, now.month, now.day, 16, 0),
        type: 'General',
        isAutoGenerated: true,
        sourceType: 'hygiene',
    ));

    return list;
  }
}
