import 'package:hive/hive.dart';

part 'reminder_model.g.dart';

@HiveType(typeId: 6)
class ReminderModel extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final String description;

  @HiveField(3)
  final DateTime scheduledTime;

  @HiveField(4)
  final bool isCompleted;

  @HiveField(5)
  final String type;

  @HiveField(6)
  final int? notificationId;

  @HiveField(7)
  final bool isAutoGenerated;

  @HiveField(8)
  final String? sourceType;

  ReminderModel({
    required this.id,
    required this.title,
    required this.description,
    required this.scheduledTime,
    this.isCompleted = false,
    required this.type,
    this.notificationId,
    this.isAutoGenerated = false,
    this.sourceType,
  });

  ReminderModel copyWith({
    String? id,
    String? title,
    String? description,
    DateTime? scheduledTime,
    bool? isCompleted,
    String? type,
    int? notificationId,
    bool? isAutoGenerated,
    String? sourceType,
  }) {
    return ReminderModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      scheduledTime: scheduledTime ?? this.scheduledTime,
      isCompleted: isCompleted ?? this.isCompleted,
      type: type ?? this.type,
      notificationId: notificationId ?? this.notificationId,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      sourceType: sourceType ?? this.sourceType,
    );
  }
}
