import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:maternal_infant_care/data/models/reminder_model.dart';
import 'package:maternal_infant_care/presentation/viewmodels/repository_providers.dart';
import 'package:maternal_infant_care/presentation/viewmodels/user_provider.dart';

final educatorSuggestionsProvider = FutureProvider<List<ReminderModel>>((ref) async {
  final userProfile = ref.watch(userProfileProvider);
  if (userProfile != UserProfileType.educator) return [];

  final reminderRepo = await ref.watch(reminderRepositoryProvider.future);
  final now = DateTime.now();
  final todayKey = '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}';

  final performance = reminderRepo.getRemindersByType('EducatorPerformance');
  if (performance.isEmpty) {
    final seed = <ReminderModel>[
      _studentPerformance('Aarav', 45, now),
      _studentPerformance('Isha', 52, now),
      _studentPerformance('Meera', 70, now),
      _studentPerformance('Rohan', 48, now),
      _studentPerformance('Zoya', 62, now),
      _studentPerformance('Vivaan', 55, now),
      _studentPerformance('Anaya', 74, now),
      _studentPerformance('Kabir', 58, now),
    ];
    for (final entry in seed) {
      await reminderRepo.saveReminder(entry);
    }
  }

  final updatedPerformance = reminderRepo.getRemindersByType('EducatorPerformance');
  final needsRevision = updatedPerformance
      .where((entry) => _parseScore(entry.description) < 60)
      .length;

  if (needsRevision == 0) {
    return [];
  }

  final suggestionId = 'educator_vowels_$todayKey';
  final suggestion = ReminderModel(
    id: suggestionId,
    title: 'Class Progress Alert',
    description: '$needsRevision students need revision in vowels.',
    scheduledTime: now,
    type: 'EducatorSuggestion',
    isAutoGenerated: true,
    sourceType: 'class_progress',
  );

  final existingIds = reminderRepo.getAllReminders().map((r) => r.id).toSet();
  if (!existingIds.contains(suggestionId)) {
    await reminderRepo.saveReminder(suggestion);
  }

  return [suggestion];
});

ReminderModel _studentPerformance(String name, int score, DateTime now) {
  return ReminderModel(
    id: 'educator_perf_${name.toLowerCase()}_${now.millisecondsSinceEpoch}',
    title: 'Student Performance',
    description: 'student=$name; vowels_score=$score',
    scheduledTime: now,
    type: 'EducatorPerformance',
    isAutoGenerated: true,
    sourceType: 'vowels',
  );
}

int _parseScore(String description) {
  final match = RegExp(r'vowels_score=(\d+)').firstMatch(description);
  if (match == null) return 0;
  return int.tryParse(match.group(1) ?? '0') ?? 0;
}
