import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:maternal_infant_care/data/models/reminder_model.dart';
import 'package:maternal_infant_care/presentation/viewmodels/repository_providers.dart';
import 'package:maternal_infant_care/presentation/viewmodels/user_provider.dart';

final parentSuggestionsProvider = FutureProvider<List<ReminderModel>>((ref) async {
  final userProfile = ref.watch(userProfileProvider);
  if (userProfile != UserProfileType.toddlerParent) return [];

  final feedingRepo = await ref.watch(feedingRepositoryProvider.future);
  final sleepRepo = await ref.watch(sleepRepositoryProvider.future);
  final diaperRepo = await ref.watch(diaperRepositoryProvider.future);
  final reminderRepo = await ref.watch(reminderRepositoryProvider.future);

  final now = DateTime.now();
  final today = DateTime(now.year, now.month, now.day);

  final feedingCount = feedingRepo.getFeedingsByDate(today).length;
  final sleepHours = sleepRepo.getTotalSleepHoursByDate(today);
  final diaperCount = diaperRepo.getDiapersByDate(today).length;

  final dateKey = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';

  final suggestions = <ReminderModel>[];

  if (sleepHours < 10) {
    suggestions.add(ReminderModel(
      id: 'parent_suggestion_attention_$dateKey',
      title: 'Improve Attention Span',
      description: 'Sleep logged today: ${sleepHours.toStringAsFixed(1)} hrs. Try a 10‑min phonics activity for focus.',
      scheduledTime: now,
      type: 'Suggestion',
      isAutoGenerated: true,
      sourceType: 'activity_ideas',
    ));
  }

  if (feedingCount < 3) {
    suggestions.add(ReminderModel(
      id: 'parent_suggestion_nutrition_$dateKey',
      title: 'Nutrition Nudge',
      description: 'Only $feedingCount meals logged today. Add a balanced snack or meal.',
      scheduledTime: now,
      type: 'Suggestion',
      isAutoGenerated: true,
      sourceType: 'feeding',
    ));
  }

  if (diaperCount < 2) {
    suggestions.add(ReminderModel(
      id: 'parent_suggestion_hygiene_$dateKey',
      title: 'Hygiene Check',
      description: 'Diaper checks are low today ($diaperCount logged). Record a check for routine tracking.',
      scheduledTime: now,
      type: 'Suggestion',
      isAutoGenerated: true,
      sourceType: 'diaper',
    ));
  }

  if (suggestions.isEmpty) {
    return [];
  }

  final existingIds = reminderRepo.getAllReminders().map((r) => r.id).toSet();
  for (final suggestion in suggestions) {
    if (!existingIds.contains(suggestion.id)) {
      await reminderRepo.saveReminder(suggestion);
    }
  }

  return suggestions;
});
